### ISSUE TITLE
Controlling key and filename fields

### ISSUE THREAD

**Issue by malfatti** [perrette/papers#16]
Hey! Thanks for sharing this very nice software!

I'm trying to generate entries with key format like `perrette2013scaling` instead of `Perrette_2013` and to rename the file as `Perrette2013_AScalingApproachToProjectRegionalSeaLevelRiseAndItsUncertainties.pdf`. Is such controlling implemented yet? If not, I could play with this and try to implement `--key-fields`  and `--filename-fields` arguments to some subcommands, where the default would be `--key-fields author,_,year` :) Would you accept pull requests?

Cheers,
Malfatti

**Comment by perrette** [comment]
Hi Malfatti, this would be certainly useful to have. I don't think I went in this direction yet, as there were - and still are - other pressing issues like bullet-proof git support and other workflow aspects (local/global install) to make the package really useful. In any case, please go ahead. As mentioned in #15 I don't think we need python 2.7 support anymore even though I'd need to find a neat way out for those in need. Just didn't find time lately. Let me know how it goes. Thanks.

**Comment by malfatti** [comment]
Hey!

Sorry for the huge delay. I finally had time to make the changes to allow the controlling I needed. You did most of the heavy work, I just had to pass the arguments to some functions and make them installable.

Cheers :)

**Comment by perrette** [comment]
Hi @malfatti, 

no reason to be sorry. That all sounds very good. I am myself so busy now and cannot give a careful look. Looking forward to coming back to it very soon.
