### ISSUE TITLE
question: is there a way to share the PDFs and metadata on a common server?

### ISSUE THREAD

**Issue by monperrus** [perrette/papers#9]
Hi,

I'm looking for a command-line tool like "paper", but I also need that the PDFs and bibtex data are shared on a common server for the whole team.

What would you recommend?

**Comment by kirk86** [comment]
I am not the developer of the library but it seems like what you're asking can easily be solved by writing a small script keeping track of the bibtex file & whenever it's updated it automatically shares stuff on the common shared server, or maybe something like rsync, sshfs, or even dropbox, gdrive and the equivalent.

**Comment by perrette** [comment]
Hi, sorry that I did not reply, this project is on hold until i have time for further development, but feel free to use it / develop it further.
In fact, something more in the spirit of the project would be to use git-lfs to keep track of the PDFs. There is already a git function for the bibtex itself.
